site_name: 'Documentació de les tasques'
theme:
  name: 'mkdocs'

nav:
  - Inici: index.md
  - Articles EDD:
    - Article 1: ENTORNS/documente_1.md
    - Article 2: ENTORNS/documente_2.md
    - Article 3: ENTORNS/documente_3.md
    - Article 4: ENTORNS/documente_4.md
    - Article 5: ENTORNS/documente_5.md
  - Articles LMI:
    - Article 1: MARQUES/documentm_1.md
  - Calculadora:
    - Calculadora whit ant: calculadora
  - HTML:
    - Activitats HTML: MARQUES/ActivitatsHTML
    - Activitat1: MARQUES/ActivitatsHTML/Exercici1.html
    - Activitat2: MARQUES/ActivitatsHTML/Exercici2.html
    - Activitat3: MARQUES/ActivitatsHTML/Exercici3.html
    - Activitat4: MARQUES/ActivitatsHTML/Exercici4.html
    - Activitat5: MARQUES/ActivitatsHTML/Exercici5.html
    - Activitat6: MARQUES/ActivitatsHTML/Exercici6.html
    - Activitat7: MARQUES/ActivitatsHTML/Exercici7.html
    - Activitat8: MARQUES/ActivitatsHTML/Exercici8.html
    - Activitat9: MARQUES/ActivitatsHTML/Exercici9.html
    - Activitat10: MARQUES/ActivitatsHTML/Exercici10.html
    - Activitat11: MARQUES/ActivitatsHTML/Exercici11.html
    - Activitat12: MARQUES/ActivitatsHTML/Exercici12.html
    - Activitat13: MARQUES/ActivitatsHTML/Exercici13.html
    - Activitat14: MARQUES/ActivitatsHTML/Exercici14.html
    - Activitat15: MARQUES/ActivitatsHTML/Exercici15.html
  - JavaScript:
    - Activitat1: javascript/Exercici1.js
    - Activitat2: javascript/Exercici2.js
    - Activitat3: javascript/Exercici3.js
    - Activitat4: javascript/Exercici4.js
    - Activitat5: javascript/Exercici5.js
    - Activitat6: javascript/Exercici6.js
    - Activitat7: javascript/Exercici7.js
    - Activitat8: javascript/Exercici8.js
    - Activitat9: javascript/Exercici9.js
    - Activitat10: javascript/Exercici10.js
    - Activitat11: javascript/Exercici11.js
    - Activitat12: javascript/Exercici12.js


    

